@startuml

title Cuiで入力されたテキストからクラス図を出力する

|Cui|
start
:コマンドでファイルパスと出力形式を指定する;
|Core|
:ファイルパスと出力形式を取得する;
if (ファイルが存在するかどうか) then (false)
  :エラーを出力し終了する;
  stop
else (true)
  :ファイルを読み込む;
  if (ファイルが読み込めなかった) then (true)
    :エラーを出力し終了する;
    stop
  else (false)
    :ファイル内のテキストをクラス図に変換する;
    if (変換に失敗した) then (true)
      :エラーを出力し終了する;
      stop
    endif
  endif
endif
:クラス図を指定された形式でファイルに出力する;
if (ファイル出力に失敗した) then (true)
  :エラーを出力し終了する;
  stop
endif
:出力先と成功した旨を出力する;
|Cui|
:出力先と成功した旨が出力される;
stop

@enduml