@startuml

' 設計方針: 契約プログラミングで設計し契約が果たせない場合、例外を投げる
' 投げる例外については、どう処理したいかで投げるものを決める
' ParseException: 入力をやり直せば正常に行けるので、再入力を促す
' OutOfMemoryException: 致命的なエラーなのでエラーが発生した旨を表示し落とす。

title エラー発生時処理

start
:ログに発生原因を書き込む;
:補足した例外を投げる;
stop

@enduml