@startuml AsciiBuilder activity diagram

title クラス図オブジェクトをAsciiに変更させるアクティビティ

start

:クラス図オブジェクトを取得;
if (クラス図オブジェクト == null) then (true)
  :エラー発生時処理;
  stop
else (false)
endif

partition 最大文字数取得 {
  :クラス名の文字数を取得;
  :属性のアクセス修飾子と名前と型を合わせた文字列で\n一番長かった文字数を取得;
  :操作のアクセス修飾子と名前と型を合わせた文字列で\n一番長かった文字列を取得;
  :クラス名と属性と操作の中で一番長い文字数を取得;
}

:StringBuilderを生成;

partition 仕切りの追加 {
  :仕切りを一番長い文字数に合わせて作成;
  :仕切りをStringBuilderに追加;
}

partition クラス名の追加 {
  :クラス名に'| 'を追加;
  :クラス名にアクセス修飾子を追加;
  :クラス名に名前を追加;
  :クラス名に' : 'を追加;
  :クラス名に型を追加;
  :クラス名に
  :クラス名に'|'を追加;
  :クラス名をStringBuilderに追加;
}

partition 属性の追加 {
  :属性に'| 'を追加;
  :属性にアクセス修飾子を追加;
  :属性に名前を追加;
  :属性に' : 'を追加;
  :属性に型を追加;
  :属性に' | 'を追加;
  :属性をStringBuilderに追加;
}

partition 操作の追加 {
  :操作に'| 'を追加;
  :操作にアクセス修飾子を追加;
  :操作に名前を追加;
  :操作に' : 'を追加;
  :操作に型を追加;
  :操作に' | 'を追加;
  :操作をStringBuilderに追加;
}

:;

stop

@enduml